# Generated by Django 4.2.7 on 2023-11-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_student_password_studentfavoritecourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '8. Course Ratings'},
        ),
    ]
