# Generated by Django 4.2.7 on 2023-11-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfavoritecourse',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
