# Generated by Django 4.2.7 on 2023-11-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_studentfavoritecourse_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfavoritecourse',
            name='teacher',
        ),
    ]
