# Generated by Django 4.2.7 on 2023-11-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_studentfavoritecourse_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfavoritecourse',
            name='teacher',
        ),
    ]
