# Generated by Django 4.2.7 on 2023-11-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_studentfavoritecourse_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfavoritecourse',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
