# Generated by Django 4.2.7 on 2023-11-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_text',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_for',
            field=models.CharField(max_length=200, verbose_name='Notification for'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifiread_status',
            field=models.BooleanField(default=False, verbose_name='Notification Status'),
        ),
    ]
