# Generated by Django 4.2.7 on 2023-11-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_coursequiz_course_alter_coursequiz_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
