# Generated by Django 4.2.7 on 2023-11-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_quizquestions_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='title',
        ),
    ]
