# Generated by Django 4.2.7 on 2023-11-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_quizquestions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequiz',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
