# Generated by Django 4.2.7 on 2023-11-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_coursequiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursequiz',
            name='title',
        ),
    ]
